### ISSUE TITLE
NoMethodError: undefined method `except' for #<Class>

### ISSUE THREAD

**Issue by chrisvariety** [ernie/valium#1]
```
ree-1.8.7-2010.02 > Menu.where(:live => true).value_of :id
NoMethodError: undefined method `except' for #<Class:0x1063fe718>
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/activerecord-3.0.0/lib/active_record/base.rb:1016:in `method_missing'
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/valium-0.2.0/lib/valium.rb:64:in `valium_select_one'
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/valium-0.2.0/lib/valium.rb:40:in `[]'
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/valium-0.2.0/lib/valium.rb:90:in `value_of'
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/activerecord-3.0.0/lib/active_record/relation.rb:120:in `scoping'
from /Users/chrismcc/.rvm/gems/ree-1.8.7-2010.02@xxx/gems/valium-0.2.0/lib/valium.rb:90:in `value_of'
from (irb):1
```

... any ideas? Happens with Menu.where(:live => true)[:id] as well. Could be related to my rails version? 3.0.0.

**Comment by ernie** [comment]
It definitely could be, but I'm looking at some other differences between 3-1-stable and 3-0-stable now.

**Comment by ernie** [comment]
Yup, it was. I'm updating the dependencies -- you'll need 3.0.2 or later to work with Valium 0.2.1. I'll yank the old ones to prevent anyone else having this nasty surprise. Thanks!

**Comment by chrisvariety** [comment]
Thanks! Works great with 3.0.10 and is sooo speeeedyyyyy.
